### ISSUE TITLE
Variables 问题

### ISSUE THREAD

**Issue by lzswangjian** [chenzhi1992/Multi-Label-Text-Classification#5]
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    main()
  File "train.py", line 148, in main
    grads_and_vars = optimizer.compute_gradients(Model.cost)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 380, in compute_gradients
    raise ValueError("No variables to optimize.")
ValueError: No variables to optimize.
------------------------------------
我用我自己的数据，图代码没有改动，报上面的错误

**Comment by rmhamei** [comment]
@lzswangjian 请问你是怎么解决wv文件这个问题的？

**Comment by lzswangjian** [comment]
@rmhamei  wv什么问题，我没有遇到啊。 我data用的自己的，不是作者提供的那个

**Comment by rmhamei** [comment]
@lzswangjian 你的vectorhelper是怎么写的？代码里没有这个文件
import vector_helper as wv
x1_batch = wv.embedding_lookup(len(x_batch_1), FLAGS.sentence_words_num, FLAGS.embedding_dim,
x_batch_1, 1)

**Comment by lzswangjian** [comment]
@rmhamei  额 我还没执行到这 就报上面的错误了，你没有遇到上面的错误么？

**Comment by rmhamei** [comment]
@lzswangjian 没有呀，import vectorhepler就在文档的前几行呀，我的代码执行到import vectorhelper这行就停了

**Comment by lzswangjian** [comment]
额 我把import vectorhelper那个先注释了，那个不重要。 可以自己替换的。 我主要是想用下那个主模型部分的代码，但是执行到构建图那边就报错了。你可以试下把那个注释掉会不会报错

**Comment by lzswangjian** [comment]
@rmhamei  
额 我把import vectorhelper那个先注释了，那个不重要。 可以自己替换的。 我主要是想用下那个主模型部分的代码，但是执行到构建图那边就报错了。你可以试下把那个注释掉会不会报错

**Comment by rmhamei** [comment]
@lzswangjian 我注释掉了之后的报错是：Traceback (most recent call last):
  File "train.py", line 42, in <module>
    FLAGS._parse_flags()
  File "/home/zhangxl/.local/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/home/zhangxl/.local/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags
